<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  
  <script>
    /*
    async 函数
    在函数前面加一个async 代表函数返回值是一个promise类型
    如果返回的不是一个promise类型的对象，则返回的结果是一个成功状态的promise, fulfilled=成功
    如果抛出错误，则返回的结果是一个失败的promise
    如果返回的结果是一个promise对象，那么这个promise对象中如果执行resolve则返回的就是成功的，并且返回的值就是resolve中的值，失败同理
    */
    async function fn() {
      return '测试返回'
    }
    const result = fn();
    console.log(result)

    async function fn1 () {
      throw new Error('报错')
    }
    const result1 = fn1()
    console.log(result1)

    async function fn2 () {
      return new Promise((resolve, reject) => {
        resolve('成功')
      })
    }
    const reulst2 = fn2()
    console.log(reulst2)

    //调用then方法
    reulst2.then(value => {
      console.log(value);
    }, err => {
      console.log(err);
    })

    /*
    await表达式
    await必须写在async函数中
    一般来说await跟的是一个promise对象，并且接受到的值就是promise中返回的值
    如果是reject的话，需要用try{}catch(e){}来捕获错误信息
    */
    const p = new Promise((resolve, reject) => {
      resolve('测试成功')
    })
    async function main () {
      let result = await p
      console.log(result)
    }
    main()
  </script>
</body>
</html>